### ISSUE TITLE
Did the view refresh every second?

### ISSUE THREAD

**Issue by vhikd** [Ciechan/BCMeshTransformView#3]
Hello,
When I add the UITableView to the BCMeshTransformView, the UITableView become very slow.
So I want to know if the BCMeshTransformView refresh the view every second.

**Comment by Ciechan** [comment]
BCMeshTransformView has to make a snapshot of `contentView` whenever a property of one of its subviews changes. In your case, the `bounds` property of `UITableView` gets implicitly changed since it gets scrolled. 

Unfortunately the snapshotting is quite slow and you won't get 60 FPS unless you're running the app on the latest device and the `UITableView` is quite small.

Little can be done to fix this, perhaps you can figure out an interaction that doesn't require the constant shanpshotting. If the content of table view is small, you could just use an overlay UIScrollView, snapshot the tableview once and modify the mesh transform on `scrollViewDidScroll:` to make the 1:1 correspondence to the offset. While this might be tricky to implement, I'm quite sure it's possible to get it working (assuming you're within the limit of 2048 points of height)
